#!/bin/env python3

import torch
from torchstat import stat
import torchvision.models as models

from model_param_analyzer import Model_param_analyzer
model_param_analyzer_obj = Model_param_analyzer()

def main():
  model_param_analyzer_obj.get_model_param(model=models.AlexNet(), model_name='AlexNet', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.alexnet(), model_name='alexnet', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.DenseNet(), model_name='DenseNet', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.GoogLeNet(), model_name='GoogLeNet', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.googlenet(), model_name='googlenet', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.Inception3(), model_name='Inception3', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.inception_v3(), model_name='inception_v3', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.MobileNetV2(), model_name='MobileNetV2', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.SqueezeNet(), model_name='SqueezeNet', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.densenet121(), model_name='densenet121', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.densenet161(), model_name='densenet161', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.densenet169(), model_name='densenet169', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.densenet201(), model_name='densenet201', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.efficientnet_b0(), model_name='efficientnet_b0', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.efficientnet_b1(), model_name='efficientnet_b1', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.efficientnet_b2(), model_name='efficientnet_b2', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.efficientnet_b3(), model_name='efficientnet_b3', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.efficientnet_b4(), model_name='efficientnet_b4', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.efficientnet_b5(), model_name='efficientnet_b5', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.efficientnet_b6(), model_name='efficientnet_b6', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.efficientnet_b7(), model_name='efficientnet_b7', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.efficientnet_v2_l(), model_name='efficientnet_v2_l', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.efficientnet_v2_m(), model_name='efficientnet_v2_m', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.efficientnet_v2_s(), model_name='efficientnet_v2_s', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.mnasnet0_5(), model_name='mnasnet0_5', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.mnasnet0_75(), model_name='mnasnet0_75', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.mnasnet1_0(), model_name='mnasnet1_0', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.mnasnet1_3(), model_name='mnasnet1_3', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.mobilenet_v2(), model_name='mobilenet_v2', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.mobilenet_v3_large(), model_name='mobilenet_v3_large', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.mobilenet_v3_small(), model_name='mobilenet_v3_small', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.regnet_x_16gf(), model_name='regnet_x_16gf', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.regnet_x_1_6gf(), model_name='regnet_x_1_6gf', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.regnet_x_32gf(), model_name='regnet_x_32gf', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.regnet_x_3_2gf(), model_name='regnet_x_3_2gf', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.regnet_x_400mf(), model_name='regnet_x_400mf', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.regnet_x_800mf(), model_name='regnet_x_800mf', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.regnet_x_8gf(), model_name='regnet_x_8gf', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.regnet_y_16gf(), model_name='regnet_y_16gf', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.regnet_y_1_6gf(), model_name='regnet_y_1_6gf', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.regnet_y_32gf(), model_name='regnet_y_32gf', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.regnet_y_3_2gf(), model_name='regnet_y_3_2gf', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.regnet_y_400mf(), model_name='regnet_y_400mf', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.regnet_y_800mf(), model_name='regnet_y_800mf', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.regnet_y_8gf(), model_name='regnet_y_8gf', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.regnet_y_128gf(), model_name='regnet_y_128gf', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.resnet101(), model_name='resnet101', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.resnet152(), model_name='resnet152', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.resnet18(), model_name='resnet18', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.resnet34(), model_name='resnet34', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.resnet50(), model_name='resnet50', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.resnext101_32x8d(), model_name='resnext101_32x8d', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.resnext101_64x4d(), model_name='resnext101_64x4d', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.resnext50_32x4d(), model_name='resnext50_32x4d', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.shufflenet_v2_x0_5(), model_name='shufflenet_v2_x0_5', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.shufflenet_v2_x1_0(), model_name='shufflenet_v2_x1_0', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.shufflenet_v2_x1_5(), model_name='shufflenet_v2_x1_5', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.shufflenet_v2_x2_0(), model_name='shufflenet_v2_x2_0', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.squeezenet1_0(), model_name='squeezenet1_0', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.squeezenet1_1(), model_name='squeezenet1_1', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.vgg11(), model_name='vgg11', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.vgg11_bn(), model_name='vgg11_bn', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.vgg13(), model_name='vgg13', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.vgg13_bn(), model_name='vgg13_bn', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.vgg16(), model_name='vgg16', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.vgg16_bn(), model_name='vgg16_bn', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.vgg19(), model_name='vgg19', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.vgg19_bn(), model_name='vgg19_bn', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.wide_resnet101_2(), model_name='wide_resnet101_2', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.wide_resnet50_2(), model_name='wide_resnet50_2', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.convnext_base(), model_name='convnext_base', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.convnext_large(), model_name='convnext_large', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.convnext_small(), model_name='convnext_small', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.convnext_tiny(), model_name='convnext_tiny', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.swin_b(), model_name='swin_b', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.swin_s(), model_name='swin_s', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.swin_t(), model_name='swin_t', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.vit_b_16(), model_name='vit_b_16', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.vit_b_32(), model_name='vit_b_32', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.vit_h_14(), model_name='vit_h_14', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.vit_l_16(), model_name='vit_l_16', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.vit_l_32(), model_name='vit_l_32', feature_map=(1,3,224,224))
  
  model_param_analyzer_obj.get_model_param(model=models.segmentation.deeplabv3_mobilenet_v3_large(), model_name='deeplabv3_mobilenet_v3_large', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.segmentation.deeplabv3_resnet101(), model_name='deeplabv3_resnet101', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.segmentation.deeplabv3_resnet50(), model_name='deeplabv3_resnet50', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.segmentation.fcn_resnet101(), model_name='fcn_resnet101', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.segmentation.fcn_resnet50(), model_name='fcn_resnet50', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.segmentation.lraspp_mobilenet_v3_large(), model_name='lraspp_mobilenet_v3_large', feature_map=(1,3,224,224))
  
  model_param_analyzer_obj.get_model_param(model=models.detection.ssd300_vgg16(), model_name='ssd300_vgg16', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.detection.ssdlite320_mobilenet_v3_large(), model_name='ssdlite320_mobilenet_v3_large', feature_map=(1,3,224,224))
  
  model_param_analyzer_obj.get_model_param(model=models.detection.fasterrcnn_mobilenet_v3_large_320_fpn(pretrained=False), model_name='fasterrcnn_mobilenet_v3_large_320_fpn', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.detection.fasterrcnn_mobilenet_v3_large_fpn(), model_name='fasterrcnn_mobilenet_v3_large_fpn', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.detection.fasterrcnn_resnet50_fpn(), model_name='fasterrcnn_resnet50_fpn', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.detection.fasterrcnn_resnet50_fpn_v2(), model_name='fasterrcnn_resnet50_fpn_v2', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.detection.maskrcnn_resnet50_fpn_v2(), model_name='maskrcnn_resnet50_fpn_v2', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.detection.maskrcnn_resnet50_fpn(), model_name='maskrcnn_resnet50_fpn', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.detection.retinanet_resnet50_fpn(), model_name='retinanet_resnet50_fpn', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.detection.retinanet_resnet50_fpn_v2(), model_name='retinanet_resnet50_fpn_v2', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.detection.keypointrcnn_resnet50_fpn(), model_name='keypointrcnn_resnet50_fpn', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.detection.fcos_resnet50_fpn(), model_name='fcos_resnet50_fpn', feature_map=(1,3,224,224))
  # model_param_analyzer_obj.get_model_param(model=models.video.mc3_18(), model_name='mc3_18', feature_map=(1,3,224,224))
  # model_param_analyzer_obj.get_model_param(model=models.video.r3d_18(), model_name='r3d_18', feature_map=(1,3,224,224))
  # model_param_analyzer_obj.get_model_param(model=models.video.r2plus1d_18(), model_name='r2plus1d_18', feature_map=(1,3,224,224))
  
  model_param_analyzer_obj.get_model_param(model=models.quantization.resnet18(), model_name='quantization-resnet18', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.quantization.resnet50(), model_name='quantization-resnet50', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.quantization.resnext101_32x8d(), model_name='quantization-resnext101_32x8d', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.quantization.resnext101_64x4d(), model_name='quantization-resnext101_64x4d', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.quantization.googlenet(), model_name='quantization-googlenet', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.quantization.shufflenet_v2_x0_5(), model_name='quantization-shufflenet_v2_x0_5', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.quantization.shufflenet_v2_x1_0(), model_name='quantization-shufflenet_v2_x1_0', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.quantization.inception_v3(), model_name='quantization-inception_v3', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.quantization.shufflenet_v2_x1_5(), model_name='quantization-shufflenet_v2_x1_5', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.quantization.shufflenet_v2_x2_0(), model_name='quantization-shufflenet_v2_x2_0', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.quantization.mobilenet_v3_large(), model_name='quantization-mobilenet_v3_large', feature_map=(1,3,224,224))
  model_param_analyzer_obj.get_model_param(model=models.quantization.mobilenet_v2(), model_name='quantization-mobilenet_v2', feature_map=(1,3,224,224))

  model_param_analyzer_obj.analysis_frequency()
  model_param_analyzer_obj.draw_analysis_statictis('torch_models')

if __name__ == "__main__":
    main()
